random_image: return the bytes, not the BytesIO object.
The `NamedImage` class that was accidentally used before  could handle this.
But with `NamedBlobImage` it resulted in a few test failures like this:

```
Failure in test Scenario A page is opened to edit in TinyMCE (test_tinymce.robot)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.9.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/6.0/src/robotsuite/src/robotsuite/__init__.py", line 514, in runTest
    assert last_status == 'PASS', last_message
AssertionError: (<InterfaceClass plone.namedfile.interfaces.IStorage>, '_io.BytesIO')
```